### PR TITLE
chore: remove duplicate content

### PR DESCRIPTION
**Pull request by threewebcode**
remove duplicate content

**Description**

A clear and concise description of the features you're adding in this pull request.

**Tests**

Please describe any tests you've added. If you've added no tests, or left important behavior untested, please explain why not.

**Additional context**

Add any other context about the problem you're solving.

**Metadata**

- Fixes #[Link to Issue]

### CODE REVIEW

**Review by tynes — APPROVED** [review]

**Comment by tynes** [comment]
Can merge once linting passes

**Comment by tynes** [comment]
@threewebcode going to close this if you don't plan on fixing the lint issues

**Comment by threewebcode** [comment]
> @threewebcode going to close this if you don't plan on fixing the lint issues

let me fix the lint issue.

**Comment by threewebcode** [comment]
> @threewebcode going to close this if you don't plan on fixing the lint issues

Done

**Review by tynes — APPROVED** [review]

**Comment by tynes** [comment]
Thank you!

**Pull request merged**
