### PR TITLE
docs(dependency-set): specify that dependency is bidirectional

### PR DESCRIPTION
**Pull request by qbzzt**
**Description**

Change the specs to match what I heard from @zainbacchus in our call today (unless I misunderstood).

**Tests**

N/A

**Additional context**

N/A

**Metadata**

N/A

### CODE REVIEW

**Comment by tynes** [comment]
I think this needs a bit more explaining, specifically around why and how. Perhaps this information isn't super legible, its part of https://github.com/ethereum-optimism/specs/pull/465

**Comment by zainbacchus** [comment]
This should be helpful: https://github.com/ethereum-optimism/docs/pull/1171

**Comment by zainbacchus** [comment]
Closing this as this change was reverted. See:https://github.com/ethereum-optimism/docs/pull/1186

**Comment by qbzzt** [comment]
I don't understand. Can chainA be in the dependency set of chainB if chainB is *not* in the dependency set of chainA? In other words, is it possible for me to send an interop message A->B, but not B->A? If so then the change I proposed is wrong. If not, it is necessary for accuracy.

Changing the docs should not affect the specs, IMAO.

**Pull request closed without merging**
