### PR TITLE
chore: fix typos

### PR DESCRIPTION
**Pull request by zhiqiangxu**
Move spec changes from https://github.com/ethereum-optimism/optimism/pull/9128 and https://github.com/ethereum-optimism/optimism/pull/9127 here.

### CODE REVIEW

**Review by ajsutton — APPROVED** [review]

**Review by ajsutton — APPROVED** [review]

**Comment by ajsutton** [comment]
@zhiqiangxu We had a config issue with CircleCI so it didn't run the required checks.  Could you merge in the latest changes from develop and hopefully it will build this time please?

**Comment by zhiqiangxu** [comment]
> @zhiqiangxu We had a config issue with CircleCI so it didn't run the required checks. Could you merge in the latest changes from develop and hopefully it will build this time please?

I guess you mean the main branch, right? I just merged with the main branch:)

**Comment by ajsutton** [comment]
Yep I meant main, sorry it's develop in the monorepo. :)

Looks like there's a [lint error](https://app.circleci.com/pipelines/github/ethereum-optimism/specs/22/workflows/19af7359-d22f-450c-9cf7-c46268bd2c82/jobs/21?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) because of the arrow change that needs to be fixed up:

```
specs/fault-proof.md:412:121 MD013/line-length Line length [Expected: 120; Actual: 123]
```

**Comment by ajsutton** [comment]
Thanks for this!

**Pull request merged**
